# Generated by Django 4.2.8 on 2024-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateidea',
            name='preferences',
            field=models.ManyToManyField(blank=True, null=True, related_name='date_ideas', to='date.preference'),
        ),
    ]
