# Generated by Django 4.2.8 on 2024-02-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0004_alter_dateidea_budget_alter_dateidea_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dateidea',
            unique_together={('name', 'description', 'budget', 'place', 'time')},
        ),
    ]
